# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for Jupyter2Tethys.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f environment.yml
#   $ conda env create --name XXX -f environment.yml

name: j2t

channels:
- pyviz
- defaults

dependencies:
- python=3.7.0
- django=2.1.5
- holoviews=1.11.2
- datashader=0.6.9
- panel=0.4.0
- geoviews=1.6.2
- python-snappy=0.5.3
- fastparquet=0.1.6
- parambokeh=0.2.3
- ipywidgets=7.4.2
- paramnb=2.0.4
- flask=1.0.2
- twisted=18.9.0
- pip:
    - channels==2.1.5
